<?xml version="1.0" encoding="utf-8"?><Database Name="db" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\db.mdf;Integrated Security=True" SettingsObjectName="services.Properties.Settings" SettingsPropertyName="dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Clients" Member="Clients">
    <Type Name="Client">
      <Column Name="client_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="client_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="client_surname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Client_Dog" Member="Dogs" ThisKey="client_id" OtherKey="dog_owner_id" Type="Dog" />
    </Type>
  </Table>
  <Table Name="dbo.Dogs" Member="Dogs">
    <Type Name="Dog">
      <Column Name="dog_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dog_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dog_owner_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Client_Dog" Member="Client" ThisKey="dog_owner_id" OtherKey="client_id" Type="Client" IsForeignKey="true" />
    </Type>
  </Table>
</Database>